name: CI Build

# Controls when the action will run. Triggers the workflow on pushed tags
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

      # Set up Node
    - name: Use Node 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
        registry-url: 'https://registry.npmjs.org'

      # Run install dependencies
    - name: Install dependencies
      run: npm i

      # Build
    - name: Build
      run: npm run prepublish

    - name: Test
      run: npm test

    - name: Test packaging
      run: npm run package
